/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    hair: THREE.SkinnedMesh
    male: THREE.SkinnedMesh
    pants: THREE.SkinnedMesh
    shirt: THREE.SkinnedMesh
    shoes: THREE.SkinnedMesh
    root: THREE.Bone
    ['MCH-torsoparent']: THREE.Bone
    ['MCH-hand_ikparentL']: THREE.Bone
    ['MCH-upper_arm_ik_targetparentL']: THREE.Bone
    ['MCH-hand_ikparentR']: THREE.Bone
    ['MCH-upper_arm_ik_targetparentR']: THREE.Bone
    ['MCH-foot_ikparentL']: THREE.Bone
    ['MCH-thigh_ik_targetparentL']: THREE.Bone
    ['MCH-foot_ikparentR']: THREE.Bone
    ['MCH-thigh_ik_targetparentR']: THREE.Bone
  }
  materials: {}
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/AvatarTest.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-0.01, 1.88, -0.12]} rotation={[0.27, 0, -0.02]}>
        <group position={[0, 0.24, 0]} rotation={[-0.15, -0.01, 0.02]}>
          <group position={[0, 0.24, 0]} rotation={[-0.06, 0, 0]}>
            <group position={[0, 0.22, 0]} rotation={[-0.09, 0, 0]}>
              <group position={[0, 0.34, 0]} rotation={[0.41, 0, 0]}>
                <group position={[0, 0.12, 0]} rotation={[0.02, 0, 0]} />
              </group>
              <group position={[0.06, 0.24, 0.19]} rotation={[-1.46, -0.14, -0.85]}>
                <group position={[0.02, 0.35, -0.11]} rotation={[1.36, 0.79, -2.11]}>
                  <group position={[0, 0.49, 0]} rotation={[0.15, 0.01, 0.04]}>
                    <group position={[0, 0.5, 0]} rotation={[0.23, -0.19, -0.35]}>
                      <group position={[0.02, 0.09, 0.04]} rotation={[-2.13, 1.28, 2.05]}>
                        <group position={[0, 0.13, 0]} rotation={[0.19, 0, -0.04]}>
                          <group position={[0, 0.08, 0]} rotation={[0.16, -0.06, 0.01]} />
                        </group>
                        <group position={[0.01, 0, 0.01]} rotation={[-1.04, 0.95, 1.84]}>
                          <group position={[0, 0.07, 0]} rotation={[0.34, -0.07, -0.09]} />
                        </group>
                      </group>
                      <group position={[0, 0.07, 0]} rotation={[-2.02, 1.17, 1.78]}>
                        <group position={[0, 0.12, 0]} rotation={[0.44, -0.02, -0.08]}>
                          <group position={[0, 0.09, 0]} rotation={[0.24, -0.09, -0.01]} />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
              <group position={[-0.06, 0.24, 0.19]} rotation={[-1.46, 0.14, 0.85]}>
                <group position={[-0.02, 0.35, -0.11]} rotation={[1.36, -0.79, 2.11]}>
                  <group position={[0, 0.49, 0]} rotation={[0.15, -0.01, -0.04]}>
                    <group position={[0, 0.5, 0]} rotation={[0.23, 0.19, 0.35]}>
                      <group position={[-0.02, 0.09, 0.04]} rotation={[-2.13, -1.28, -2.05]}>
                        <group position={[0, 0.13, 0]} rotation={[0.19, 0, 0.04]}>
                          <group position={[0, 0.08, 0]} rotation={[0.16, 0.06, -0.01]} />
                        </group>
                        <group position={[-0.01, 0, 0.01]} rotation={[-1.04, -0.95, -1.84]}>
                          <group position={[0, 0.07, 0]} rotation={[0.34, 0.07, 0.09]} />
                        </group>
                      </group>
                      <group position={[0, 0.07, 0]} rotation={[-2.02, -1.17, -1.78]}>
                        <group position={[0, 0.12, 0]} rotation={[0.44, 0.02, 0.08]}>
                          <group position={[0, 0.09, 0]} rotation={[0.24, 0.09, 0.01]} />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <group position={[0.21, 0.04, 0.15]} rotation={[2.86, 0, -0.13]}>
          <group position={[0, 0.83, 0]} rotation={[0.08, 0.02, 0.02]}>
            <group position={[0, 0.86, 0]} rotation={[-1.06, -0.08, 0.12]} />
          </group>
        </group>
        <group position={[-0.2, 0.03, 0.14]} rotation={[2.86, 0.02, 0.09]}>
          <group position={[0, 0.83, 0]} rotation={[0.08, -0.02, -0.02]}>
            <group position={[0, 0.86, 0]} rotation={[-1.06, 0.08, -0.12]} />
          </group>
        </group>
      </group>
      <primitive object={nodes.root} />
      <primitive object={nodes['MCH-torsoparent']} />
      <primitive object={nodes['MCH-hand_ikparentL']} />
      <primitive object={nodes['MCH-upper_arm_ik_targetparentL']} />
      <primitive object={nodes['MCH-hand_ikparentR']} />
      <primitive object={nodes['MCH-upper_arm_ik_targetparentR']} />
      <primitive object={nodes['MCH-foot_ikparentL']} />
      <primitive object={nodes['MCH-thigh_ik_targetparentL']} />
      <primitive object={nodes['MCH-foot_ikparentR']} />
      <primitive object={nodes['MCH-thigh_ik_targetparentR']} />
      <skinnedMesh castShadow geometry={nodes.hair.geometry} material={nodes.hair.material} skeleton={nodes.hair.skeleton} />
      <skinnedMesh castShadow geometry={nodes.male.geometry} material={nodes.male.material} skeleton={nodes.male.skeleton} />
      <skinnedMesh castShadow geometry={nodes.pants.geometry} material={nodes.pants.material} skeleton={nodes.pants.skeleton} />
      <skinnedMesh castShadow geometry={nodes.shirt.geometry} material={nodes.shirt.material} skeleton={nodes.shirt.skeleton} />
      <skinnedMesh castShadow geometry={nodes.shoes.geometry} material={nodes.shoes.material} skeleton={nodes.shoes.skeleton} />
    </group>
  )
}

useGLTF.preload('/AvatarTest.glb')
