/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube001_1: THREE.Mesh
    Cube001_2: THREE.Mesh
    Cube002_1: THREE.Mesh
    Cube002_2: THREE.Mesh
    Cube_1: THREE.Mesh
    Cube_2: THREE.Mesh
    Cube_3: THREE.Mesh
    Cylinder022: THREE.Mesh
    Cube003: THREE.Mesh
    Cube004: THREE.Mesh
    Cube005: THREE.Mesh
    Cube006_1: THREE.Mesh
    Cube006_2: THREE.Mesh
    Cube007: THREE.Mesh
    Cube008: THREE.Mesh
    Cube009: THREE.Mesh
    Cube010: THREE.Mesh
    Cube011: THREE.Mesh
    Cube012: THREE.Mesh
    Cube013: THREE.Mesh
    Cube015: THREE.Mesh
    Cylinder003_1: THREE.Mesh
    Cylinder003_2: THREE.Mesh
    Cylinder003_3: THREE.Mesh
    Cylinder003_4: THREE.Mesh
    Cylinder007_1: THREE.Mesh
    Cylinder007_2: THREE.Mesh
    Cylinder007_3: THREE.Mesh
    Cylinder004: THREE.Mesh
    Cylinder006: THREE.Mesh
    Cylinder004_1: THREE.Mesh
    Cylinder004_2: THREE.Mesh
    Cube016: THREE.Mesh
    Cube017: THREE.Mesh
    Cube018: THREE.Mesh
    Cube019: THREE.Mesh
    Cube020: THREE.Mesh
    Cube021: THREE.Mesh
    Cube022: THREE.Mesh
    Cube023: THREE.Mesh
    Cube024: THREE.Mesh
    Cube025: THREE.Mesh
    Cube026: THREE.Mesh
    Cube028: THREE.Mesh
    Cube029: THREE.Mesh
    Cube030: THREE.Mesh
    Cube031_1: THREE.Mesh
    Cube031_2: THREE.Mesh
    Cube032: THREE.Mesh
    Cube033: THREE.Mesh
    Cube034: THREE.Mesh
    Cube035: THREE.Mesh
    Cube036: THREE.Mesh
    Cube037: THREE.Mesh
    Cube038: THREE.Mesh
    Cube039: THREE.Mesh
    Cylinder009_1: THREE.Mesh
    Cylinder009_2: THREE.Mesh
    Cylinder009_3: THREE.Mesh
    Cylinder010_1: THREE.Mesh
    Cylinder010_2: THREE.Mesh
    Cylinder010_3: THREE.Mesh
    Cylinder011: THREE.Mesh
    Cylinder012: THREE.Mesh
    Cylinder013: THREE.Mesh
    Cube040: THREE.Mesh
    Cube041: THREE.Mesh
    Cube042: THREE.Mesh
    Cube043: THREE.Mesh
    Cube044: THREE.Mesh
    Cube045: THREE.Mesh
    Cube046: THREE.Mesh
    Cube047: THREE.Mesh
    Cube048: THREE.Mesh
    Cube049: THREE.Mesh
    Cube050: THREE.Mesh
    Cube027: THREE.Mesh
    Cube052: THREE.Mesh
    Cube053: THREE.Mesh
    Cube064: THREE.Mesh
    Cylinder014_1: THREE.Mesh
    Cylinder014_2: THREE.Mesh
    Cube054: THREE.Mesh
    Cylinder015: THREE.Mesh
    Cylinder016: THREE.Mesh
    Cube055: THREE.Mesh
    Cylinder017: THREE.Mesh
    Cylinder018: THREE.Mesh
    Cube051: THREE.Mesh
    Cylinder: THREE.Mesh
    Cube001: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cube002: THREE.Mesh
    Cube: THREE.Mesh
    Cube014: THREE.Mesh
    Cube056: THREE.Mesh
    Cube057: THREE.Mesh
    Cylinder005: THREE.Mesh
    Cylinder008: THREE.Mesh
    Sphere: THREE.Mesh
    Cylinder019: THREE.Mesh
    Cube063_1: THREE.Mesh
    Cube063_2: THREE.Mesh
    Cylinder020: THREE.Mesh
    Cylinder021: THREE.Mesh
    Cube060: THREE.Mesh
    Cube061: THREE.Mesh
    Cube062: THREE.Mesh
    Cube063: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    ['dark metal']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['metal 2']: THREE.MeshStandardMaterial
    metal: THREE.MeshStandardMaterial
    Wing: THREE.MeshStandardMaterial
    ['light metal']: THREE.MeshStandardMaterial
    ['white base']: THREE.MeshStandardMaterial
    ['accent 2']: THREE.MeshStandardMaterial
    accent: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    Droid: THREE.MeshStandardMaterial
    ['droid accent']: THREE.MeshStandardMaterial
    lens: THREE.MeshStandardMaterial
    ['Ladder material']: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/XWing.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Cube001_1.geometry} material={nodes.Cube001_1.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube001_2.geometry} material={nodes.Cube001_2.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube002_1.geometry} material={materials['Material.002']} />
      <mesh castShadow receiveShadow geometry={nodes.Cube002_2.geometry} material={nodes.Cube002_2.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube_1.geometry} material={materials.Material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube_2.geometry} material={nodes.Cube_2.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube_3.geometry} material={nodes.Cube_3.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder022.geometry} material={nodes.Cylinder022.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube006_1.geometry} material={nodes.Cube006_1.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube006_2.geometry} material={nodes.Cube006_2.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube007.geometry} material={nodes.Cube007.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube008.geometry} material={nodes.Cube008.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube009.geometry} material={nodes.Cube009.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube010.geometry} material={nodes.Cube010.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube011.geometry} material={nodes.Cube011.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube012.geometry} material={nodes.Cube012.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube013.geometry} material={nodes.Cube013.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube015.geometry} material={nodes.Cube015.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder003_1.geometry} material={nodes.Cylinder003_1.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder003_2.geometry} material={nodes.Cylinder003_2.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder003_3.geometry} material={nodes.Cylinder003_3.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder003_4.geometry} material={nodes.Cylinder003_4.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder007_1.geometry} material={nodes.Cylinder007_1.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder007_2.geometry} material={nodes.Cylinder007_2.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder007_3.geometry} material={nodes.Cylinder007_3.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder004.geometry} material={nodes.Cylinder004.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder006.geometry} material={nodes.Cylinder006.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder004_1.geometry} material={nodes.Cylinder004_1.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder004_2.geometry} material={nodes.Cylinder004_2.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube016.geometry} material={nodes.Cube016.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube017.geometry} material={nodes.Cube017.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube018.geometry} material={nodes.Cube018.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube019.geometry} material={nodes.Cube019.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube020.geometry} material={nodes.Cube020.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube021.geometry} material={nodes.Cube021.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube022.geometry} material={nodes.Cube022.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube023.geometry} material={nodes.Cube023.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube024.geometry} material={nodes.Cube024.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube025.geometry} material={nodes.Cube025.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube026.geometry} material={nodes.Cube026.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube028.geometry} material={nodes.Cube028.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube029.geometry} material={nodes.Cube029.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube030.geometry} material={nodes.Cube030.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube031_1.geometry} material={nodes.Cube031_1.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube031_2.geometry} material={nodes.Cube031_2.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube032.geometry} material={nodes.Cube032.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube033.geometry} material={nodes.Cube033.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube034.geometry} material={nodes.Cube034.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube035.geometry} material={nodes.Cube035.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube036.geometry} material={nodes.Cube036.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube037.geometry} material={nodes.Cube037.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube038.geometry} material={nodes.Cube038.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube039.geometry} material={nodes.Cube039.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder009_1.geometry} material={nodes.Cylinder009_1.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder009_2.geometry} material={nodes.Cylinder009_2.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder009_3.geometry} material={nodes.Cylinder009_3.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder010_1.geometry} material={nodes.Cylinder010_1.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder010_2.geometry} material={nodes.Cylinder010_2.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder010_3.geometry} material={nodes.Cylinder010_3.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder011.geometry} material={nodes.Cylinder011.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder012.geometry} material={nodes.Cylinder012.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder013.geometry} material={nodes.Cylinder013.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube040.geometry} material={nodes.Cube040.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube041.geometry} material={nodes.Cube041.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube042.geometry} material={nodes.Cube042.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube043.geometry} material={nodes.Cube043.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube044.geometry} material={nodes.Cube044.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube045.geometry} material={nodes.Cube045.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube046.geometry} material={nodes.Cube046.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube047.geometry} material={nodes.Cube047.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube048.geometry} material={nodes.Cube048.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube049.geometry} material={nodes.Cube049.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube050.geometry} material={nodes.Cube050.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube027.geometry} material={nodes.Cube027.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube052.geometry} material={nodes.Cube052.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube053.geometry} material={nodes.Cube053.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube064.geometry} material={nodes.Cube064.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder014_1.geometry} material={materials['Material.003']} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder014_2.geometry} material={nodes.Cylinder014_2.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube054.geometry} material={nodes.Cube054.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder015.geometry} material={nodes.Cylinder015.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder016.geometry} material={nodes.Cylinder016.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube055.geometry} material={nodes.Cube055.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder017.geometry} material={nodes.Cylinder017.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder018.geometry} material={nodes.Cylinder018.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube051.geometry} material={nodes.Cube051.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube.geometry} material={nodes.Cube.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube014.geometry} material={nodes.Cube014.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube056.geometry} material={nodes.Cube056.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube057.geometry} material={nodes.Cube057.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder005.geometry} material={nodes.Cylinder005.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder008.geometry} material={nodes.Cylinder008.material} />
      <mesh castShadow receiveShadow geometry={nodes.Sphere.geometry} material={materials.Droid} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder019.geometry} material={nodes.Cylinder019.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube063_1.geometry} material={materials['droid accent']} />
      <mesh castShadow receiveShadow geometry={nodes.Cube063_2.geometry} material={materials.lens} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder020.geometry} material={nodes.Cylinder020.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder021.geometry} material={nodes.Cylinder021.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube060.geometry} material={nodes.Cube060.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube061.geometry} material={nodes.Cube061.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube062.geometry} material={nodes.Cube062.material} />
      <mesh castShadow receiveShadow geometry={nodes.Cube063.geometry} material={nodes.Cube063.material} />
    </group>
  )
}

useGLTF.preload('/XWing.glb')
